Feature/backend 1879
balmbees/corgi pull request #47
Opened 2018-10-30 06:30 UTC by breath103

Currently, when error occurs corgi format error without stackTrace since it can leak internal structure of system.

in order to debug error easily, 
1) if you set **CORGI_ERROR_PASSWORD**
2) error response would have "metadata" which is encrypted stackTrace + error message
3) you can decrypt this with same key

2018-10-31 02:50 UTC, deerFried approved these changes
👍

2018-10-31 03:50 UTC, syeutyu approved these changes

2018-10-31 09:01 UTC, mooyoul requested changes

2018-10-31 09:01 UTC, mooyoul commented on src/error_response.ts
> +              cipher.update(JSON.stringify({
const payload = JSON.stringify(obj);

return Buffer.concat([
  cipher.update(payload),
  cipher.final(),
]).toString('hex');

로 쓰는게 어떨까요?

2018-11-01 01:55 UTC, breath103 commented on src/error_response.ts
> +            const cipher = crypto.createCipher(CipherAlgorithm, this.password)
createCipheriv 로 하려면 HMAC key도 만들어야 해서 너무 복잡하긴 한데.. 검토는 해볼께요

2018-11-01 02:08 UTC, breath103 commented
HMAC 까지는 안하고 IV 키만 추가해서 끝냈습니다.

2018-11-01 02:16 UTC, merged